######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 24 06:59:27 2009
######################################################################

TEMPLATE = app
TARGET = rubikai
DESTDIR = ../bin/linux_x86/
OBJECTS_DIR = ../bin/linux_x86/
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += RubikAI.h
SOURCES += main.cpp RubikAI.cpp
